### ISSUE TITLE
Where is efetch.batch() function?

### ISSUE THREAD

**Issue by jelber2** [gschofl/reutils#2]
I tried using reutils_0.1.2's efetch function and get the following error

> fasta <- reutils::efetch(uid = mRNA.acc, db = "nucleotide", rettype = "gb")
You are attempting to download 19952 records.
Only the first 500 are downloaded. Use efetch.batch() instead.

When I try looking for efetch.batch() function, it does not seem to exist in reutils. Did it exist in a previous version?

>reutils::efetch.batch()
Error: 'efetch.batch' is not an exported object from 'namespace:reutils'

**Comment by gschofl** [comment]
Oops, yes, this is a leftover from an older version. I'll look into it. For now a workaround for you would be to split your UIDs into packages of 500 and loop over them. Just be sure to include something like `Sys.sleep(0.5)` in the loop to make sure you don't place to many API calls per second to the NCBI servers.

**Comment by gschofl** [comment]
Now fixed in the development version. You have to make sure, however, to provide the UIDs as a reference to an NCBI Web Env (i.e. use `esearch(..., usehistory = TRUE)` or `epost(...)`) and you have to write the data to a file (there's a new option `outfile` now in `efetch()`)

Also, compare the last example in the documentation for `efetch()`

**Comment by jelber2** [comment]
I tried the fix to efetch.
First I used epost:
> post2 <- epost(mRNA.gi, "nuccore")

Then, I tried calling efetch,
> mRNA.acc2 <- efetch(uid = mRNA.gi, db = "nuccore", rettype = "acc", retmode = "text", outfile = "mRNA.acc2.txt", webenv = post2)

And keep getting the following error:
>Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘webenv’ for signature ‘"character"’

Am I doing something wrong?

**Comment by gschofl** [comment]
You have to pass the `epost` object as `uid` to `efetch`. Like so;
```r
post2 <- epost(mRNA.gi, "nuccore")
efetch(uid = post2, rettype = "acc", retmode = "text", outfile = "mRNA.acc2.txt")
```

or in one go:
```r
efetch(epost(mRNA.gi, db = "nuccore"), rettype = "acc", retmode = "text", outfile = "mRNA.acc2.txt")
```

**Comment by jelber2** [comment]
Both suggestions work, but I can only download the first 10000 records even
after adjusting retmax.

**Comment by gschofl** [comment]
Hopefully works now for you. The following code snippet, for instance, downloads 18567 records successfully.

```r
s <- esearch("phospholipase [PROT]", "protein", retmax = 20000)
p <- epost(s)
efetch(p, rettype = "fasta", retmode = "text", outfile = "phospholipase.fna")
```
