### ISSUE TITLE
Table of databases moved

### ISSUE THREAD

**Issue by lmmx** [gschofl/reutils#4]
The table of databases you link to [in the README](https://github.com/gschofl/reutils#efetch) has moved from [here](http://www.ncbi.nlm.nih.gov/books/NBK25499/table/chapter4.chapter4_table1) to [here](http://www.ncbi.nlm.nih.gov/books/NBK25499/table/chapter4.T._valid_values_of__retmode_and/?report=objectonly)

**Comment by gschofl** [comment]
Fixed, thanks.
