### ISSUE TITLE
esummary doesn't get first record from an epost

### ISSUE THREAD

**Issue by jmacdon** [gschofl/reutils#6]
> esummary(epost("929249993", "nuccore"))
Object of class  esummary  
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD esummary nuccore 20150326//EN" "http://eutils.ncbi.nlm.nih.gov/eutils/dtd/20150326/esummary_nuccore.dtd">
<eSummaryResult>
  <DocumentSummarySet status="OK">
</DocumentSummarySet>
</eSummaryResult>
 
ESummary query using the database  nuccore .

But if I use two, I get one returned. If I were to use 500, I would get 499 - just not the first one.

> esummary(epost(c("929249993","929249993"), "nuccore"))
Object of class  esummary  
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eSummaryResult PUBLIC "-//NLM//DTD esummary nuccore 20150326//EN" "http://eutils.ncbi.nlm.nih.gov/eutils/dtd/20150326/esummary_nuccore.dtd">
<eSummaryResult>
  <DocumentSummarySet status="OK">
    <DocumentSummary uid="929249993">
      <Caption>XM_014145730</Caption>
      <Title>PREDICTED: Salmo salar DENN/MADD domain containing 2C (dennd2c), transcript variant X3, mRNA</Title>
      <Extra>gi|929249993|ref|XM_014145730.1|</Extra>
      <Gi>929249993</Gi>
      <CreateDate>2015/09/21</CreateDate>
      <UpdateDate>2015/09/21</UpdateDate>
      <Flags>512</Flags>
      <TaxId>8030</TaxId>
      <Slen>4918</Slen>
      <Biomol>mRNA</Biomol>
      <MolType>rna</MolType>
      <Topology>linear</Topology>
      <SourceDb>refseq</SourceDb>
      <SegSetSize>0</SegSetSize>
      <ProjectId>287919</ProjectId>
      <Genome>genomic</Genome>
      <SubType>sex|tissue_type|dev_stage|chromosome</SubType>
      <SubName>female|muscle|adult|ssa15</SubName>
      <AssemblyGi>0</AssemblyGi>
      <AssemblyAcc/>
      <Tech/>
      <Completeness/>
      <GeneticCode>1</GeneticCode>
      <Strand/>
      <Organism>Atlantic salmon</Organism>
      <Strain/>
      <Statistics>
        <Stat type="Length" count="4918"/>
        <Stat type="Length" subtype="literal" count="4918"/>
        <Stat type="all" count="3"/>
        <Stat type="blob_size" count="6845"/>
        <Stat type="cdregion" count="1"/>
        <Stat type="cdregion" subtype="CDS" count="1"/>
        <Stat type="gene" count="1"/>
        <Stat type="gene" subtype="Gene" count="1"/>
        <Stat type="org" count="1"/>
        <Stat source="CDS" type="all" count="1"/>
        <Stat source="CDS" type="prot" count="1"/>
        <Stat source="CDS" type="prot" subtype="Prot" count="1"/>
        <Stat source="all" type="Length" count="4918"/>
        <Stat source="all" type="all" count="4"/>
        <Stat source="all" type="blob_size" count="6845"/>
        <Stat source="all" type="cdregion" count="1"/>
        <Stat source="all" type="gene" count="1"/>
        <Stat source="all" type="org" count="1"/>
        <Stat source="all" type="prot" count="1"/>
      </Statistics>
      <Properties na="1">1</Properties>
      <OSLT indexed="yes">XM_014145730.1</OSLT>
      <AccessionVersion>XM_014145730.1</AccessionVersion>
    </DocumentSummary>
  </DocumentSummarySet>
</eSummaryResult>
 
ESummary query using the database  nuccore .
> 

Is this a bug, or just me doing things the wrong way?

Jim

**Comment by jmacdon** [comment]
I forgot to add

> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reutils_0.2.2.9000 devtools_1.9.1    

loaded via a namespace (and not attached):
 [1] httr_1.0.0     compiler_3.2.2 assertthat_0.1 R6_2.1.1       magrittr_1.5  
 [6] tools_3.2.2    RCurl_1.95-4.7 curl_0.9.4     memoise_0.2.1  stringi_1.0-1 
[11] stringr_1.0.0  digest_0.6.8   bitops_1.0-6   XML_3.98-1.3  
>

**Comment by gschofl** [comment]
Fixed in the development version on github.
Thanks for reporting!
Gerhard
