### ISSUE TITLE
Change base URLs for NCBI services to use https instead of http

### ISSUE THREAD

**Issue by elucify** [gschofl/reutils#7]
To improve end user security and privacy, and by Federal government mandate OMB memo M-08-023, NCBI will be moving all web services to HTTPS-only by September 30, 2016.

Looking over your source code, I notice that the eutilities base URL starts with http://

This code needs to be updated to use https:// URLs instead. While we intend to provide redirects for GET and HEAD, POST and other non-safe methods will be rejected with HTTP 403; in particular, epost will cease to function over http when we move to https.

For more information:

http://www.ncbi.nlm.nih.gov/news/06-10-2016-ncbi-https/
https://https.cio.gov/
subscribe to the utilities-announce mailing list at https://www.ncbi.nlm.nih.gov/mailman/listinfo/utilities-announce

**Comment by gschofl** [comment]
Fixed in 0.2.3.
Thanks
