### ISSUE TITLE
Support for API Key

### ISSUE THREAD

**Issue by RamRS** [gschofl/reutils#9]
Hello,

Starting May 2018, NCBI restricts eutils queries to 3 per second, and this limit is increased to 10 per second with an API key. reutils does not have a provision to supply an API key as far as I can see. Could this be programmed in please?

**Comment by gschofl** [comment]
Support for API keys is now implemented. You might want to use the GitHub version until the update is pushed to CRAN. Set `options(reutils.api.key = "YourAPIkey")` interactively or in your `.Rprofile` file.
